default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  username: postgres
  password: postgres
  timeout: 5000

development:
  <<: *default
  database: tutu_development

test:
  <<: *default
  database: tutu_test

production:
  <<: *default
  database: tutu_production
